# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-19 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permohonan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contractor', models.CharField(max_length=50)),
                ('contractor_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=11)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=500)),
                ('request_status', models.CharField(choices=[('P', 'Dalam Permohonan'), ('T', 'Ditolak'), ('L', 'Diluluskan')], default='P', max_length=1)),
            ],
        ),
    ]
