# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-19 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permohonan',
            options={'permissions': (('can_approve', 'Can approve Permohonan'), ('can_reject', 'Can reject Permohonan'), ('can_submit', 'Can submit Permohonan'))},
        ),
    ]
